In [2]:
import os
import pyreadr as pyr
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

#### Álgebra lineal con Numpy

In [3]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [4]:
### Se puede usar la función np.arange
c = np.arange(1, 8)
c

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
### Un vector con todos los elemento iguales a 1
d = np.ones(3)
d

array([1., 1., 1.])

In [7]:
### Transponiendo el vector
np.transpose(b)

array([1, 2, 3])

### Suma y resta de vectores

In [8]:
x = np.array([1, 5])
y = np.array([2, 4])

x + y

array([3, 9])

In [9]:
### La resta es similar
x - y

array([-1,  1])

### Multiplicación por un escalar

In [11]:
x * 4

array([ 4, 20])

In [12]:
y * 6

array([12, 24])

### Producto escalar

In [13]:
np.dot(x, y)

np.int64(22)

### Norma de un vector

In [14]:
np.linalg.norm(x)

np.float64(5.0990195135927845)